source 'https://rubygems.org'
ruby '1.9.3'

gem 'rails', '3.2.13'

gem 'active_attr'
gem 'aws'
gem 'bcrypt-ruby', require: 'bcrypt'
gem 'bootstrap-sass'
gem 'bson_ext'
gem 'carrierwave'
gem 'carrierwave_direct'
gem 'carrierwave-mongoid', :require => 'carrierwave/mongoid'
gem 'client_side_validations'
gem 'daemons'
gem 'delayed_job_mongoid'
gem 'devise'
gem 'expedia'
gem 'fog', '~> 1.3.1'
gem 'haml'
gem 'hashie'
gem 'hpricot'
gem 'jquery-rails'
gem 'kaminari'
gem 'less-rails'
gem 'libxml-ruby'
gem 'mini_magick'
gem 'mongoid', '~> 3.0.0'
gem 'mongoid_fulltext'
gem 'nokogiri'
gem 'rb-fsevent', '~> 0.9.1'
gem 'ruby_parser'
gem 'sanitize'
gem 'sass-rails',   '~> 3.2.3'
gem 'sidekiq'
gem 'simple_form'
gem 'sinatra'
gem 'slim'
gem 'subexec'
gem 'therubyracer'

group :assets do
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :test, :development do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'erb2haml'
  gem 'faker'
  gem 'factory_girl_rails'
  gem 'guard-rspec'
  gem 'html2haml'
  gem 'pry'
  gem 'pry-debugger'
  gem 'pry-stack_explorer'
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'steak'
  gem 'shoulda-matchers'
end
